### ISSUE TITLE
OBS Settings not applying

### ISSUE THREAD

**Issue by raresuta** [auraside/HoneCtrl#14]
When i Try To Apply  The Obs Recording settings, they dont apply, one of the owners, ryan said to me that i should make sure that obs is closed, i closed it and tried again, it didn't work, then he said that i should try running it as admin, i did it, it didn't work again ( i had obs closed ) please fix this bug in the next update

**Comment by RadNotRed** [comment]
The settings should apply, what one are you trying to do?

**Comment by RadNotRed** [comment]
Also just tested, they all work perfectly fine if you watch `%appdata%\obs-studio\basic\profiles\Untitled\basic.ini`

**Comment by elitee78** [comment]
> When i Try To Apply The Obs Recording settings, they dont apply, one of the owners, ryan said to me that i should make sure that obs is closed, i closed it and tried again, it didn't work, then he said that i should try running it as admin, i did it, it didn't work again ( i had obs closed ) please fix this bug in the next update

U have a other language i think, so create a new profile in OBS named "Untitled" and it works!
