### ISSUE TITLE
TimerResolution - outated

### ISSUE THREAD

**Issue by NotAspects** [auraside/HoneCtrl#16]
Windows has not taken into account the modification of Timer for more than 2-3 years.

![image](https://user-images.githubusercontent.com/73410229/182023098-b725cdfe-3def-4b3c-8b1d-66034b8f67bc.png)

![image](https://user-images.githubusercontent.com/73410229/182023109-6fe2af33-7a5b-4666-8c67-4fc99a526bec.png)

**Comment by Vojtazz** [comment]
timer resolution matters only in 1909 and lower, version should be checked

**Comment by rn9551** [comment]
This has been added to this list, we'll check for the 1909 windows version in a future update, thanks
