### ISSUE TITLE
Cannot log in when using Office (2021/365)

### ISSUE THREAD

**Issue by Pixel-SharpZero** [auraside/HoneCtrl#18]
hello
I always use HoneCtrl
When activating Office, when it is uploaded to OneDrive,
After entering the email address on the login screen, the screen to enter the password is not displayed,
Freeze

This sentence uses Google translation, so it may be strange in places, but thank you for your understanding

==========Environment==========
CPU: Core i3-12100
RAM: DDR4-2666 8GB
SSD: 128GB
===============================

**Comment by couleurm** [comment]
imo there should be warnings for people that use Xbox / UWP / Microsoft Apps/Store kinda stuff

**Comment by Pixel-LASSY** [comment]
excuse me
I don't know where the warning is
sorry to bother you
Please write where such a description is found

**Comment by Realjonathah** [comment]
> imo there should be warnings for people that use Xbox / UWP / Microsoft Apps/Store kinda stuff

Services and debloat section are closed since a bit. Aside from those we don't touch anything uwp related

**Comment by rn9551** [comment]
Hey,

What version of honectrl do you currently have installed?

**Comment by Pixel-LASSY** [comment]
@Realjonathah
I understand
Thank you for your answer

@rn9551 
返信ありがとうございます
バージョンは 2.53 です

**Comment by rn9551** [comment]
@Pixel-LASSY

Are you sure that this is a honectrl issue? What option did you enable?

**Comment by Pixel-LASSY** [comment]
@rn9551 
thank you for your reply
When you enable the following services in HoneCtrl, you will not be able to log in.

#Optimizations
   SvcHostSplitThreshold
   CSRSS High Priority
   Timer Resolution
   MSI Mode
   Affinity
   Memory Optimization
   Mouse Fix value=150
   Disable Mitigations
   Optimize TCP/IP
   Optimize NIC
   Optimize Netsh
   All GPU Tweaks
   Optimize Intel iGPU
#Advanced
   Disable Task Offloading
   NonBestEffortLimit
   AutoTuning
   DSCP Value
   Wifi Congestion Provider
   Disable C-States
   Disable Idle
   BCDEdit
   Disable USB Power Savings

**Comment by Pixel-LASSY** [comment]
@rn9551 

please reply

**Comment by Pixel-LASSY** [comment]
@rn9551

please reply

**Comment by Pixel-SharpZero** [comment]
@rn9551 
@couleurm 
@Realjonathah 
@standayweb 

Please Reply

**Comment by couleurm** [comment]
なたの状況にあった場合、オンラインでエラーを調べます。 他のすべてが失敗した場合、最良かつ最も過激なオプションは、ハードディスクを消去して Windows OS を再インストールすることです。
