### ISSUE TITLE
Potential security risks and outdated software

### ISSUE THREAD

**Issue by vladaad** [auraside/HoneCtrl#2]
All external files and software are currently downloaded from external links.
Using DDU as an example, the version that's hosted on Discord by you doesn't have the same hash as the official download for the newest version and as such may be outdated or potentially modified. 
Not only that, DDU's zip can be easily downloaded with CURL without having to rely on Discord as a CDN.

**Comment by couleurm** [comment]
https://ftp.nluug.nl/pub/games/PC/guru3d/ddu/[Guru3D.com]-DDU.zip
this one static and always redirects to latest 👍
