### ISSUE TITLE
Colors & layout don't work right on Win7

### ISSUE THREAD

**Issue by dotexe1337** [auraside/HoneCtrl#21]
Using Win7 ultimate 64-bit, colors & layout are all wacky:

![image](https://user-images.githubusercontent.com/41847745/186564937-2e09029f-6ae0-427f-9380-c6e9d82121f0.png)
![image](https://user-images.githubusercontent.com/41847745/186564954-652ada28-027a-49ee-b893-34ca397112ca.png)

My computer keeps beeping at me too when running this script.
Not sure what is wrong, I'm not really a batch scripter. Seems it doesn't like the `%COL%` thing.
Tried with cmd.exe & PowerShell.

**Comment by dotexe1337** [comment]
Interestingly enough, it works just fine when ran through ConEmu:

![image](https://user-images.githubusercontent.com/41847745/186566203-143020f0-bded-4f82-b208-1d674bebf213.png)

So, whatever Microsoft's doing just isn't happy with it for some reason.

**Comment by ViniciusRed** [comment]
The code was made for windows 10
Some things will work and some things won't as file download by curl

**Comment by couleurm** [comment]
if you can mess with the path that leads to curl.exe you can most probably get it workin 👍

https://curl.haxx.se/windows/

**Comment by rn9551** [comment]
Thanks for the insight @dotexe1337, (assuming the registry changes are still being applied), do you mind leaving a list of basic instructions for using honectrl through conEMU? I'll make a brief tutorial for a windows 7 users & credit you for it

In regards to the issue at hand, we're aware that windows 7 doesn't have native support for color formatting in ANSI, so we tried to implement the fix that was shown here: [](https://stackoverflow.com/questions/16755142/how-to-make-win32-console-recognize-ansi-vt100-escape-sequences)

This however doesn't seem to work so the only real resolution for us is to tell everyone that the panel only works on windows 10 & above.

**Comment by dotexe1337** [comment]
> do you mind leaving a list of basic instructions for using honectrl through conEMU?

It's the same as with CMD, just open up ComEmu, cd into the directory and run HoneCtrl. ConEmu defaults to Windows command shell.

**Comment by couleurm** [comment]
you could make it detect win 7, then download conemu and launch honectrl with it before showing any fancy ansi
https://github.com/Maximus5/ConEmu/releases/

**Comment by steven2024** [comment]
This program seems to work better for 8.1/7 - ([cmder](https://cmder.app/).) It doesn't need to be set up like ConEmu and it is also portable.
