### ISSUE TITLE
Host all files on the repo.

### ISSUE THREAD

**Issue by Aetopia** [auraside/HoneCtrl#3]
Basically have all files that are being downloaded by HoneCtrl, be hosted on the GitHub repository instead of invoking them via Discord.

**Comment by Realjonathah** [comment]
I've made a pull request addressing this issue, only the Nvidia profile inspector profiles will stay as discord CDN's for the moment since Github has no proper download links for text files in repos. Closing this issue

**Comment by Aetopia** [comment]
![image](https://user-images.githubusercontent.com/41850963/174342461-c20052f1-319f-49c9-bfea-78c56d3c4b26.png)

Click on the raw button of the file.

![image](https://user-images.githubusercontent.com/41850963/174342353-babeed22-1175-464c-9d9b-d139642c7c1c.png)

**Comment by Realjonathah** [comment]
seems I was trying to download  HoneCtrl/raw/main    instead of HoneCtrl/main, works now thanks

**Comment by couleurm** [comment]
yeah you can put your version in a txt and host it there instead of pastebin

**Comment by Realjonathah** [comment]
Planned, we're focusing on fixing bugs atm
