### ISSUE TITLE
Migrate to entirely PowerShell?

### ISSUE THREAD

**Issue by Aetopia** [auraside/HoneCtrl#30]
I was wondering if Hone is gonna ever migrate this entire project to PowerShell?

PowerShell has a superior feature set as compared to Batch, so why not leverage that?

**Comment by luke-beep** [comment]
Won't happen.

**Comment by Selyss** [comment]
Powershell is not a very capable scripting language compared to batch or bash

**Comment by luke-beep** [comment]
What is this tomfoolery I'm witnessing? Power shell is a very powerful scripting environment.

**Comment by Selyss** [comment]
> What is this tomfoolery I'm witnessing? Power shell is a very powerful scripting environment.

I don't know if the code is robust enough to adapt to powershell... I simply meant that batch scripting is easy to do, and bash scripting has a big support base.

**Comment by Selyss** [comment]
> we've already secretly converted everything to powershell lol. It's gud

Is it going to be pushed? I'd be interested in seeing it. Hopefully it makes the code a little easier to contribute to, as I feel like a 4k long batch file is kinda hard to digest

**Comment by JonathahWasTaken** [comment]
uhhh uhhhh *intense sweating* it's gonna be closed source for the new app d:

**Comment by couleurm** [comment]
> gonna be closed source for the new app

good luck close sourcing C# / PowerShell code, will look forward to it :)

**Comment by luke-beep** [comment]
I'll do my best.

**Comment by JonathahWasTaken** [comment]
I said closed sourced but it ain't going to be top confidential government security. If anything it's just to prevent idiots from copying our stuff.

**Comment by couleurm** [comment]
> I'll do my best.
😂😂
