### ISSUE TITLE
Messed up my computer. HELP Please.

### ISSUE THREAD

**Issue by AwsomeGamer4060** [auraside/HoneCtrl#32]
when I turn- the  Settings off and restart there is a Color problem on the top of my laptop screen and other things on my laptop gets messed up. Please help me,

**Comment by SnowzNZ** [comment]
Explain?

**Comment by Jordan231111** [comment]
you should have created registry backup before installing any scripts, just restore registry pretty sure the app should have auto backed up too..

**Comment by techgamers2** [comment]
hone bat tweaks are pretty standard and safe as compared to other tweak bat file most hone tweaks u can do manually in registry  /windows settings . and if u mess up something ( which usually doesnt happens unless u using advanced tweaks ) u can easily revert back back opening hone control panel bat and setting it to off

**Comment by luke-beep** [comment]
> https://www.wagnardsoft.com/forums/viewtopic.php?t=4699

> https://github.com/Wagnard/display-drivers-uninstaller
