### ISSUE TITLE
App crashes when I  press 1

### ISSUE THREAD

**Issue by Brandonbr1** [auraside/HoneCtrl#33]
Hello so if I type in 1  it crashes

using HoneCtrl 2.56

everthing else works

**Comment by Cris--** [comment]
Also here on Windows 11 22H2 Build 22621.1105

**Comment by jacobtb2004** [comment]
Could be an issue with the windows build. I have the same build as you and it also crashes when i press 1.
![image](https://user-images.githubusercontent.com/11246856/214342326-30dfce1c-159d-4751-9175-475aadca6fea.png)
Windows 11 22H2 Build 22621.1105

**Comment by Brandonbr1** [comment]
I am using a different windows 11 version:https://prnt.sc/0r_DyTA-nV5D

**Comment by JonathahWasTaken** [comment]
WMIC needs to be installed in optional features.
