### ISSUE TITLE
javaw.exe priority changes automatically to normal

### ISSUE THREAD

**Issue by RaziJemniXD** [auraside/HoneCtrl#36]
im not sure if this caused by honectrl or not
im trying to change javaw.exe priority in task manager but it always changes back to normal each time and tab again to the game

i dont have any program that control priorities and i couldnt find any registry that does this
so i think its caused by minecraft 1.8.9 game settings modified by honectrl.bat

**Comment by Hwaanx** [comment]
You don't need to set java to high priority, nothing changes it doesn't affect fps
