### ISSUE TITLE
ffmpeg upscaling make the audio bad 

### ISSUE THREAD

**Issue by AuraGx** [auraside/HoneCtrl#37]
so I was using hone upscaling (ffmpeg) to put my video in 4k from 1080p and when I play the video the audio was a bad quality can you fix that please

**Comment by lem6ns** [comment]
> so I was using hone upscaling (ffmpeg) to put my video in 4k from 1080p and when I play the video the audio was a bad quality can you fix that please

@JonathahWasTaken use `-c:a copy` for upscaling settings
