### ISSUE TITLE
Internet/ping problem

### ISSUE THREAD

**Issue by paprykx** [auraside/HoneCtrl#42]
When i use optimize TCP/IP and Optimize NIC and Optimize Netsh i have big latency of my internet. I have 300 - 400 pings (i m not use wi-fi)

**Comment by Hwaanx** [comment]
Honestly most of the internet tweaks are useless only useful things are probably setting mtu, disabling nagle and default ttl i can't name more

**Comment by Eratas** [comment]
Use TCP Optimizer instead for now, I guess.

**Comment by couleurm** [comment]
> Only useful things are probably setting mtu, disabling nagle and default ttl

Has anyone ever proven their usefulness, I'd be curious to have a link if so 😋?

**Comment by Hwaanx** [comment]
default ttl and setting mtu is only useful if you are having problems and want to test it out see if its any better it doesn't increase performance directly setting nagle is only useful in some games

**Comment by couleurm** [comment]
> default ttl and setting mtu is only useful if you are having problems and want to test it out see if its any better it doesn't increase performance directly setting nagle is only useful in some games

hey, you seem to know your shit, where can we discuss?

**Comment by Eratas** [comment]
I litterally said, use TCP Optimizer, everything he said is available on their documentations.
