### ISSUE TITLE
i can't open page two in optimication tweaks

### ISSUE THREAD

**Issue by jere-a** [auraside/HoneCtrl#44]
^^^^^^ Title

**Comment by devmcyt** [comment]
SAMEEE WTF IS THIS MAN

**Comment by Jordan231111** [comment]
is perf fine for me, maybe something with ur pc

**Comment by luke-beep** [comment]
Open it with elevated permissions.

**Comment by luke-beep** [comment]
> winmgmt /verifyrepository

> winmgmt /salvagerepository

> winmgmt /resetrepository

> net stop winmgmt
> net start winmgmt

Try using `wmic os get name` after that.

If that doesn't work you can try using this.

> `cd /d %windir%\system32\wbem
for %i in (*.dll) do RegSvr32 -s %i
for %i in (*.exe) do %i /RegServer`
