### ISSUE TITLE
"[ 1 ] Selecting Optimizations" closes the command prompt window

### ISSUE THREAD

**Issue by ghost** [auraside/HoneCtrl#47]
"[ 1 ] Selecting Optimizations" closes the command prompt window
Works fine except for "[ 1 ] Selecting Optimizations"

### comment
This message uses Google translation, so some sentences may be strange.
Please let me know if you can't read
(If you can't communicate well, you may write in Japanese.)

**Comment by JonathahWasTaken** [comment]
WMIC needs to be installed in optional features

**Comment by chien3553** [comment]
> 

I installed WMIC but it's not working
