### ISSUE TITLE
Memory optimizations -> Disable background apps problem

### ISSUE THREAD

**Issue by Lokimitsu** [auraside/HoneCtrl#49]
Games from the Microsoft Store seem to count as apps (f.ex. "Sea of Thieves")
and lose connection when the game window loses focus.

This is caused by "Disable Background apps" under "Memory optimizations".
Can you make it its own menu entry so we can still get the other tweaks?

**Comment by luke-beep** [comment]
Do the following to disable those tweaks;

reg delete "HKCU\Software\Microsoft\Windows\CurrentVersion\BackgroundAccessApplications" /v "GlobalUserDisabled" /f

reg delete "HKLM\Software\Policies\Microsoft\Windows\AppPrivacy" /v "LetAppsRunInBackground" /f

reg delete "HKCU\Software\Microsoft\Windows\CurrentVersion\Search" /v "BackgroundAppGlobalToggle" /f

I'd assume that would bring them back to their default values.

**Comment by Lokimitsu** [comment]
Yes you're right, I just put REM in front of them so the lines wont be executed, but not everyone knows how to do that

**Comment by luke-beep** [comment]
That works as well 👍

**Comment by techgamers2** [comment]
can u explain memory optimization tweaks more does it also enable [Empty Standby list cleaner](https://[wj32.org](https://wj32.org/wp/software/empty-standby-list/)/wp/software/empty-standby-list/) ? or do i need to need my [ISLC](https://www.wagnardsoft.com/forums/viewtopic.php?t=1256) running

**Comment by luke-beep** [comment]
This is ISLC -> https://github.com/luke-beep/MMF/blob/master/Program.cs.
