### ISSUE TITLE
i cant use the nvidia tweaks part bc it says i dont have an nvidia gpu but i do (i have a 1660 super)

### ISSUE THREAD

**Issue by masmiddel** [auraside/HoneCtrl#54]
titel says it all

**Comment by masmiddel** [comment]
the intel cpu part is fucked aswell

**Comment by masmiddel** [comment]
intel cpu part also doesnt work

**Comment by masmiddel** [comment]
i got nvidia tweaks to work
but intel still says n/a

**Comment by luke-beep** [comment]
> https://www.wagnardsoft.com/forums/viewtopic.php?t=4699
> https://www.techpowerup.com/nvcleanstall/
