### ISSUE TITLE
Is there a setting that makes the fans run more?

### ISSUE THREAD

**Issue by Blergonos** [auraside/HoneCtrl#55]
The title says it all. I'm using a laptop and the fans running 24/7 on the desktop with no games running is very annoying. If there is a setting that does that tell me how to slow it down or turn off.

**Comment by ArandomHitman** [comment]
what settings do you have enabled in the advanced settings category? (it's category 6)

**Comment by luke-beep** [comment]
No, but consider disabling the C-State & Disable Idle options. Or if you'd like to keep them on download [Fan Control](https://github.com/Rem0o/FanControl.Releases) and manually set your [fan curves](https://getfancontrol.com/docs/).

**Comment by Globalfirestorm10** [comment]
> The title says it all. I'm using a laptop and the fans running 24/7 on the desktop with no games running is very annoying. If there is a setting that does that tell me how to slow it down or turn off.

do you happen to have power plan activated? that might also cause it

**Comment by luke-beep** [comment]
> > The title says it all. I'm using a laptop and the fans running 24/7 on the desktop with no games running is very annoying. If there is a setting that does that tell me how to slow it down or turn off.
> 
> do you happen to have power plan activated? that might also cause it

That's what I referred to. C-States and Disable Idle.

**Comment by Globalfirestorm10** [comment]
ah mb

**Comment by Blergonos** [comment]
sorry for no replies for a while. Im closing this because this is a stupid question of mine, since im using high performance plan

**Comment by luke-beep** [comment]
> sorry for no replies for a while. Im closing this because this is a stupid question of mine, since im using high performance plan

Okay.
