### ISSUE TITLE
How to configure system timer tool to set 1ms instead of 0.5ms

### ISSUE THREAD

**Issue by techgamers2** [auraside/HoneCtrl#56]
my pc works well with 1ms when i set via islc but 0.5ms cause heat issues

**Comment by luke-beep** [comment]
Set it to 1ms in ISLC.

**Comment by techgamers2** [comment]
i already know tht ... i want to ditch islc and set timer resolution as a service

**Comment by luke-beep** [comment]
Hone isn't the creator of the Timer Resolution Service. 

> https://forums.guru3d.com/threads/windows-timer-resolution-tool-in-form-of-system-service.376458/
