### ISSUE TITLE
mouse priority is nt working properly

### ISSUE THREAD

**Issue by sanjeev23895** [auraside/HoneCtrl#60]
i need old hone ctrl plz provide  me that old one bcz in the old one my mouse cursor appearing in screen while playing minecraft fix but using the new hone mouse priority i cant fix this and when i use the old hone it fix this problems plz help me i dont wana to use the new hone give me old hone mouse priority is not working properly 
plzzzzzzzzzzzzz

**Comment by luke-beep** [comment]
> https://github.com/auraside/HoneCtrl/releases/tag/2.7

> `reg add "HKLM\Software\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\csrss.exe\PerfOptions" /v CpuPriorityClass /t Reg_DWORD /d "4" /f`
`reg add "HKLM\Software\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\csrss.exe\PerfOptions" /v IoPriority /t Reg_DWORD /d "3" /f`
