### ISSUE TITLE
issues starting the windows event viewer after using hone

### ISSUE THREAD

**Issue by ohi2u** [auraside/HoneCtrl#61]
I get a 4201 error when starting the event viewer service on 2 pcs that i ran hone on. before I run my restore is there anything I can do to fix this?

**Comment by luke-beep** [comment]
> Press Win + R.
> Type services.msc and press Enter.
> Find and open the properties of the Windows Event Log service, then set the startup type to automatic. 
> If the service is not running, click the Start button.

> Run `sfc /scannow` in an elevated command prompt instance. 

> Ensure that the SYSTEM, Administrators, and EventLog entries have full control over the `C:\Windows\System32\winevt\Logs` folder.
